name: CI/CD Pipeline for Laravel

on:
  push:
    branches:
      - main # Run the pipeline when code is pushed to the main branch
  pull_request:
    branches:
      - main # Also run on pull requests to main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-22.04
    needs: build # Deployment only happens after the build passes

    steps:
    # Step 1: Check out code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy to the server
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/black/property
          git pull origin main
          composer install --no-dev --optimize-autoloader
          npm install --production
          php artisan migrate --force
